server: #서버포트설정
     port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gsw?serverTimezone=Asia/Seoul
    username: gongsik-local
    password: gongsik1204local